# name: codecov
# on: [push]
# jobs:
#   run:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, macos-latest, windows-latest]
#     env:
#       OS: ${{ matrix.os }}
#       PYTHON: '3.11'
#     steps:
#     - uses: actions/checkout@master
#     - name: Setup Python
#       uses: actions/setup-python@master
#       with:
#         python-version: 3.11
#     - name: Install dependencies
#       run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#     - name: Generate coverage report
#       run: |
#         pip install pytest
#         pip install pytest-cov
#         pytest --cov=./ --cov-report=xml
#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v3
#       with:
#         files: ./coverage.xml
#         fail_ci_if_error: true
#         flags: unittests
#         name: codecov-umbrella
#         verbose: true